baseURL = "https://laymoth.dev"
title   = "Laymoth"
languageCode = "en-us"
theme = "hello-friend-ng"
defaultContentLanguage = "id"

PygmentsCodeFences = true
PygmentsStyle = "dracula"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = false
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/:title/"

[author]
  name = "Laymoth"

[blackfriday]
  hrefTargetBlank = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  # 
  description = "Laymoth's personal website."
  keywords = "laymoth, lymth"
  images = [""]

  # Home subtitle of the index page.
  #
  homeSubtitle = "Nocturnal."

  # Set a background for the homepage
  # backgroundImage = "assets/images/background.jpg"

  # Prefix of link to the gt commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/laymoth/laymoth.github.io/commit/"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  #
  disableReadOtherPosts = false
  enableThemeToggle = true
  enableSharingButtons = false
  enableGlobalLanguageMenu = false
  justifyContent = false  # Set "text-align: justify" to .post-content.

  [params.footer]
    trademark = true
    rss = false
    copyright = false
    author = false

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = "$"
    logoText     = "~/"
    logoHomeLink = "/"

 [params.portrait]
   path     = "https://avatars.githubusercontent.com/u/22806461?v=4"
   alt      = "Avatar"
   maxWidth = "100px"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/alinuxkt"

  [[params.social]]
    name = "github"
    url  = "https://github.com/laymoth"

  [[params.social]]
    name = "patreon"
    url  = "https://patreon.com/laymoth"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@laymoth:matrix.org"

[languages]
  [languages.en]
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.id]
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
